### ISSUE TITLE
The user is undefined after a page refresh.

### ISSUE THREAD

**Issue by michalczaplinski** [sw-yx/react-netlify-identity#1]
A page refresh logs a user out. This behaviour can be seen in the example linked in the README.

### To reproduce:
Go to https://netlify-gotrue-in-react.netlify.com/

I can log in by providing by the url to my identity service: https://dropclub.netlify.com
- user: mmczaplinski@gmail.com
- password: 1234

After logging in I'm redirected to `/dashboard`. Then, when I refresh the page I am redirected back to the login page and I can see that `user` is `undefined` in the console.

I was under the impression that gotrue-js should be storing the user information in `localStorage` for me. Is this functionality outside of the scope of this package or would you expect it to work?

**Comment by sw-yx** [comment]
indeed i expect gotrue-js would store it in localstorage. i am wondering if theres some CORS issue here.

**Comment by sw-yx** [comment]
fixed in https://github.com/sw-yx/react-netlify-identity/releases/tag/0.0.7 i think - please lmk if it doesnt

**Comment by b-reklass** [comment]
Hey @sw-yx this is fixed on production but doesn't appear to be fixed when testing @ localhost. Would be nice to have this for testing.

**Comment by sw-yx** [comment]
hey @michalczaplinski and @b-reklass turns out it might be my fault - see this PR https://github.com/sw-yx/react-netlify-identity/pull/2

**Comment by michalczaplinski** [comment]
@sw-yx Sorry, I went with another solution for auth in the meantime, but I ll definitely use this on another project and let you know how it works. Thanks for the great work ! :)

**Comment by sw-yx** [comment]
no problem. i made this when i was just learning, but i use this project more intensively now so ive ironed out a few more flaws sicne then.
