### ISSUE TITLE
Confirmation not working

### ISSUE THREAD

**Issue by YChebotaev** [sw-yx/react-netlify-identity#12]
Please, take a look at my app: https://github.com/YChebotaev/gsom-gsom/

[Here](https://github.com/YChebotaev/gsom-gsom/blob/master/src/components/AuthorizationGuard.jsx) I wrote code to handle urls with invite_token. It redirects to confirm page when it see invite_token= in url.

And it is not working.

Please can you disable handling routes in this library?

**Comment by sw-yx** [comment]
hi! acknowledged but i dont have time to fix this right away - if you'd like to send in a PR to disable handling routes, i'd be happy to accept.

**Comment by sw-yx** [comment]
i believe this is released in v0.1.8!
