### ISSUE TITLE
Cannot resolve dependency 'react' when running Reach example

### ISSUE THREAD

**Issue by QuantumInformation** [sw-yx/react-netlify-identity#26]
![image](https://user-images.githubusercontent.com/216566/69997498-32ab3400-154c-11ea-8e6f-965d7df440e7.png)

**Comment by QuantumInformation** [comment]
Meh, just gonna use the reach router as that seems to be the way things are moving

**Comment by QuantumInformation** [comment]
Reopened as I get this error when running locally using parcel

 example@1.0.0 start /Users/nikos/WebstormProjects/react-netlify-identity/examples/example-reach-router
> parcel index.html

Server running at http://localhost:1234 
🚨  /Users/nikos/WebstormProjects/react-netlify-identity/examples/example-reach-router/node_modules/@reach/router/es/index.js:12:18: Cannot resolve dependency 'react'
  10 | 
  11 | /* eslint-disable jsx-a11y/anchor-has-content */
> 12 | import React from "react";
     |                  ^
  13 | import warning from "warning";
  14 | import PropTypes from "prop-types";
  15 | import invariant from "invariant";

maybe use CRA instead? I've found parcel to be problematic with ts

**Comment by sw-yx** [comment]
weird. not sure whats wrong. no time to investigate this at the moment

**Comment by lindskogen** [comment]
I had this issue with parcel and it turned out that I accidentally installed reach router in the parent directory of my project, which led to it being unable to find react from there.

**Comment by sw-yx** [comment]
oops :)
