### ISSUE TITLE
Usage when developing locally? 

### ISSUE THREAD

**Issue by ljosberinn** [sw-yx/react-netlify-identity#27]
Currently, logging in automatically redirects me to the live netlify site and logs me in there as the redirect is that domain too, naturally. But obviously I'd like to be logged in on localhost.

A localhost URL is invalid, however, which makes sense since locally there's no identity lambda.

Right now I'm copying localstorage from live over to localhost which is annoying and probably not intended.

Do I miss something obvious or is this simply not supported right now?

Sidenote: running with netlify dev in case that changes anything.

**Comment by sw-yx** [comment]
not supported right now. since this is a userland library i unfortunately cant do anything about what netlify does to redirect you when you login (it just always assumes you want to be redirected to the deployed url rather than localhost). however i think it still works for email/password auth, the redirect is only required for social provider oauth?

**Comment by ljosberinn** [comment]
Yep, that works. Understandable, a bit annoying to develop on, but I'll get it done. Thanks!

**Comment by frednomoon** [comment]
@sw-yx this is a bit of an annoying one for me while working on some login / signup side-effects. Do you think it might be possible? Would be happy to work on a PR myself but just wondering if you think its achievable or not

**Comment by sw-yx** [comment]
like i said there is nothing you can do from "userland" to change how netlify identity works like this,  you'd need to supply a callbackUrl param or similar. you can submit it through Netlify's official channels as a feature request, but fyi its not going to be very high on the priority list

**Comment by reyemtm** [comment]
Has anyone found an answer or workaround for this? For the vanilla js widget there is some logic for using on localhost - https://github.com/netlify/netlify-identity-widget/blob/9f30259a8e78b8b9c64a24967575976f7463850f/src/netlify-identity.js#L96
would be great to pull this logic into this react version.
