### ISSUE TITLE
recoverAccount workflow

### ISSUE THREAD

**Issue by ljosberinn** [sw-yx/react-netlify-identity#28]
Hi, so I've been tinkering with a reset-password route for a while and found this issue:

- [x] request a password recovery via `requestPasswordRecovery(mail)` -> netlify sends out reset mail
- `runRoutes` triggers and... well, [does nothing](https://github.com/sw-yx/react-netlify-identity/blob/master/src/runRoutes.tsx#L25) - which I guess is fine, just a heads up in the docs would've been nice
- [x] so I circumvented this by [catching the recovery token myself and rerouting it to my route](https://github.com/ljosberinn/current-react-playground/blob/master/src/App.js#L33)
- [x] [there](https://github.com/ljosberinn/current-react-playground/blob/master/src/routes/public/ResetPasswordRoute/ConfirmPasswordResetForm.js#L50), [`recoverAccount(token)`](https://github.com/sw-yx/react-netlify-identity/blob/master/src/index.tsx#L154) fetches a User object based on the verified token but performs no login, valid too
- [x] while this happens, the user can enter his new password and then submit
- I'm now in possession of a regular User object, together with a valid JWT through the token and the new password - I should now be able to update the password via `updateUser({ password })` - but because `recoverAccount(token)` didn't change any lib internal state, it throws the [`are you logged in`](https://github.com/sw-yx/react-netlify-identity/blob/master/src/index.tsx#L158) error.
- so I manually [feed the token-verification User obj](https://github.com/ljosberinn/current-react-playground/blob/master/src/routes/public/ResetPasswordRoute/ConfirmPasswordResetForm.js#L47) to the lib because after the state change, `user` is no longer null
- [x] it finally executes `user!.update(fields).then(_setUser)` [in another effect](https://github.com/ljosberinn/current-react-playground/blob/master/src/routes/public/ResetPasswordRoute/ConfirmPasswordResetForm.js#L81) where I have to ignore errors thrown from the lib - not sure why these are triggered

It's finally working but imo that's a mess. Am I doing something massively wrong here?

**Comment by sw-yx** [comment]
i dont think so. im not sure why i commented out that line in runRoutes. i think there was a PR complaining about this a while back but i dont think i accepted it.

in any case - please feel free to PR what you think should be done - you have clearly done  all the necessary research to fully understand this problem. I’m not currently active on this project right now but could very well come back to it at any time

**Comment by ljosberinn** [comment]
Brainstorming here a little, let me know if this is over the top.

- have `recoverAccount(token)` trigger `_setUser` which performs a login (and also return the userObj to the dev, still)
  - it would then be the developers duty to redirect him to whatever route that allows him to change password based on...
- have `runRoutes` return an obj of shape
```js
{
 token: string | undefined,
 type: 'confirmation' | 'invite' | 'recovery' | 'email_change' | 'access' | 'confirmation' | undefined
}
```
which sets it to a new internal state `param` which gets returned from the hook so developers can just use
```js
const { replace } = useHistory();
const { param: { token, type }, user } = useIdentityContext();

if(token) {
  switch(type) {
    case 'recovery':
        replace('/settings/change-password');
        break;
    // etc
  }

  return null;
}

```
Also, `recoverAccount(token)` and all other functions using `token` would need to consume said token and remove it afterwards.

**Comment by sw-yx** [comment]
this is an interesting approach! i was tempted to suggest returning an array of tokens, but realistically i dont think that is ever going to happen. so i think this works. if you'd like to try a PR, be my guest, if not i'll take a crack whenever i get back to this
