### ISSUE TITLE
Using with Google Auth

### ISSUE THREAD

**Issue by jdbence** [sw-yx/react-netlify-identity#29]
On Netlify, I have the Google identity enabled and using the default config.
When I attempt to auth using ```loginProvider('google')```, I can see the src does a redirect to the configured url ending in ```"/.netlify/identity/authorize?provider=google"``` The issue is it shows my app and not the Google auth screen. Any ideas what I'm missing?

I'm using a CRA and it looks like it's an issue when using the ServiceWorker. If I go into chrome and disable the ServiceWorker, I get to the Google Auth screen.

**Comment by jdbence** [comment]
In order to get this to work with a CRA, I had to create a custom workbox config and black list urls that start with `/.netlify`. CRA already checks for `/_` so not sure if this lib can change from `.netlify` to `_netlify` or at-least make that configurable.

```JS
navigateFallbackBlacklist: [
    new RegExp("^/.netlify"),
    new RegExp("^/_"),
    new RegExp("/[^/?]+\\.[^/]+$")
]
```

**Comment by ljosberinn** [comment]
I've noticed that behaviour with CRA service worker too but hadn't investigated yet why this happens. Thanks for a temporary solution!

**Comment by sw-yx** [comment]
thanks everyone.. netlify has to use the `/.netlify/` namespace so i dont see that changing at all. whatever else we can do on the client or service worker side, we'll have to do that

**Comment by Skagevang** [comment]
navigateFallbackWhitelist with those RegExp will make all subdomains stop working offline. I can't seem to find a solution for making both things work?
