### ISSUE TITLE
You Removed core files

### ISSUE THREAD

**Issue by donaldboulton** [sw-yx/react-netlify-identity#33]
Tried to update to v2.0.6

Now I am getting the below error not only on v2.0.6 but all lower versions to.

Can't resolve './react-netlify-identity-widget.cjs.production.min.js' in 'C:\Users\Donald Boulton\Documents\GitHub\publiuslogic\publiuslogic\node_modules\react-netlify-identity-widget\dist'

File: node_modules\react-netlify-identity-widget\dist\index.js

They do not exist and removed from all packages I tried???

Why would you do this?

Spent a lot of time integrating this and now its not usable = and done intentionally

**Comment by sw-yx** [comment]
can you clarify what package is v2.0.6? nothing we are talking about is even v2. this repo is currently at v0.2.2.

breaking the package is not intentional. at all. but i need your help to figure out what went wrong, please dont get mad and assume ill intent.

**Comment by donaldboulton** [comment]
Sorry the above is for React Netlify Identity Widget v 2.0.6 and it does not have all the files on a npm install got v2.0.5 to work issue  closed

Apologies I was a little pissed but I tried to install v2.0.6 with npm and yarn and got the above errors.
v2.05 works

**Comment by sw-yx** [comment]
i made a bad publish, the build broke and those files were not published. should be fixed with https://github.com/sw-yx/react-netlify-identity-widget/releases/tag/v0.2.7
