### ISSUE TITLE
Cookie storage after following confirmation link

### ISSUE THREAD

**Issue by levindixon** [sw-yx/react-netlify-identity#34]
Hi @sw-yx 👋 

After a user signs up they receive a link to verify their email, when they click that link they're redirected to the application but it looks like the `gotrue.user` isn't stored.

Not sure if this is expected behavior or a bug, is the user expected to login again after following the email verification link?

Thanks!

**Comment by sw-yx** [comment]
its probably a bug, i'll take your PR
